/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionary;

import com.sun.security.ntlm.Client;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import newpackage.Voice;

/**
 *
 * @author Dan_Pham
 */
public class doHoa extends javax.swing.JFrame {
    protected DictionaryCommandline commandline=new DictionaryCommandline();
	DefaultListModel<String> model=new DefaultListModel<>();
        doHoaXoa dhx=new doHoaXoa();
         doHoaThem dht=new doHoaThem();
        
    /**
     * Creates new form doHoa
     */
    public doHoa() {
        initComponents();
        getContentPane().setBackground(Color.ORANGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTarget = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtExplain = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Từ điển");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTarget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTargetKeyReleased(evt);
            }
        });
        getContentPane().add(txtTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 32, 150, 33));

        jButton1.setText("Dịch");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 37, 93, -1));

        txtExplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExplainActionPerformed(evt);
            }
        });
        getContentPane().add(txtExplain, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 32, 151, 33));

        list.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 83, 150, 308));

        jButton2.setText("Thêm từ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 83, 93, -1));

        jButton3.setText("Xóa từ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 134, 93, -1));

        jButton4.setText("Sửa từ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 184, 93, -1));

        jButton5.setText("Phát âm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 241, 93, -1));

        jButton6.setText("Lưu thay đổi");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 304, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //if(commandline.management.dictionary.word.size()==0) commandline.management.insertFromFile();
    private void txtExplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExplainActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtExplainActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(commandline.management.dictionary.word.size()==0) commandline.management.insertFromFile();
        for(int i=0;i<commandline.management.dictionary.word.size();i++) {
            if(commandline.management.dictionary.word.get(i).word_target.equalsIgnoreCase(txtTarget.getText())) {
		txtExplain.setText(commandline.management.dictionary.word.get(i).word_explain);
		break;
            }
	}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
//        if(commandline.management.dictionary.word.size()==0) commandline.management.insertFromFile();
//        txtTarget.setText((String) list.getSelectedValue());
//            for(int i=0;i<commandline.management.dictionary.word.size();i++) {
//		if(commandline.management.dictionary.word.get(i).word_target.equalsIgnoreCase(txtTarget.getText())) {
//                    txtExplain.setText(commandline.management.dictionary.word.get(i).word_explain);
//		break;
//		}
//            }
    }//GEN-LAST:event_jButton1MouseClicked

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyReleased

    private void txtTargetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTargetKeyReleased
        // TODO add your handling code here:
        model.clear();
	if(commandline.management.dictionary.word.isEmpty())  commandline.management.insertFromFile();
	for(int i=0;i<commandline.management.dictionary.word.size();i++) {
            if(commandline.management.dictionary.word.get(i).word_target.startsWith(txtTarget.getText())) {
		model.addElement(commandline.management.dictionary.word.get(i).word_target);
            }
	}
	list.setModel(model);
    }//GEN-LAST:event_txtTargetKeyReleased

    private void listAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_listAncestorAdded

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        // TODO add your handling code here:
        txtTarget.setText((String) list.getSelectedValue());
	for(int i=0;i<commandline.management.dictionary.word.size();i++) {
            if(commandline.management.dictionary.word.get(i).word_target.equalsIgnoreCase(txtTarget.getText())) {
		txtExplain.setText(commandline.management.dictionary.word.get(i).word_explain);
		break;
            }
	}
    }//GEN-LAST:event_listMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(commandline.management.dictionary.word.size()==0) commandline.management.insertFromFile();
	dhx.setVisible(true);
//	for(int i=0;i<commandline.management.dictionary.word.size();i++) {
//            if(commandline.management.dictionary.word.get(i).word_target.equalsIgnoreCase(dhx.a) ){
//		commandline.management.dictionary.word.remove(i);
//		break;
//            }
//	}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        if(commandline.management.dictionary.word.size()==0) commandline.management.insertFromFile();
        doHoaSua dhs=new doHoaSua();
        dhs.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(commandline.management.dictionary.word.size()==0) commandline.management.insertFromFile();
        //        doHoaThem dht=new doHoaThem();
        dht.setVisible(true);
        //commandline.management.dictionary.word.add(new Word(dht.getA(),dht.getB()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Voice a = new Voice();
        a.setLine(txtTarget.getText());
        a.speak();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        commandline.management.dictionary.word.clear();
        commandline.management.insertFromFile();
        JOptionPane.showMessageDialog(rootPane, "lưu thành công");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doHoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    private javax.swing.JTextField txtExplain;
    private javax.swing.JTextField txtTarget;
    // End of variables declaration//GEN-END:variables
}
